export const CLIENT_ID = '442973200160-si3h4jb3e4bkbrt0gulqp71qdgi3bva8.apps.googleusercontent.com';

export const ZALORA_EURO_TOKEN = 'ZALORA_EURO_TOKEN';
export const ZALORA_EURO_PROFILE_ID = 'ZALORA_EURO_PROFILE_ID';
export const ZALORA_EURO_PROFILE_NAME = 'ZALORA_EURO_PROFILE_NAME';
export const ZALORA_EURO_PROFILE_EMAIL = 'ZALORA_EURO_PROFILE_EMAIL';